config/routes.rb
LeoDroid::Application.routes.draw do
  resources :dudes

  root :to => "dudes#index"

end

app/models/dude.rb
class Dude < ActiveRecord::Base
  attr_accessible :age, :last_name, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dudes_controller.rb
class DudesController < ApplicationController
  # GET /dudes
  # GET /dudes.json
  def index
    @dudes = Dude.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dudes }
      format.xml { render :xml => @dudes }
    end
  end

  # GET /dudes/1
  # GET /dudes/1.json
  def show
    @dude = Dude.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dude }
      format.xml { render :xml => @dude }
    end
  end

  # GET /dudes/new
  # GET /dudes/new.json
  def new
    @dude = Dude.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dude }
      format.xml { render :xml => @dude }
    end
  end

  # GET /dudes/1/edit
  def edit
    @dude = Dude.find(params[:id])
  end

  # POST /dudes
  # POST /dudes.json
  def create
    @dude = Dude.new(params[:dude])

    respond_to do |format|
      if @dude.save
        format.html { redirect_to @dude, notice: 'Dude was successfully created.' }
        # format.json { render json: @dude, status: :created, location: @dude }
        format.json { render xml: @dude, status: :created, location: @dude }
      else
        format.html { render action: "new" }
        # format.json { render json: @dude.errors, status: :unprocessable_entity }
        format.json { render xml: @dude.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dudes/1
  # PUT /dudes/1.json
  def update
    @dude = Dude.find(params[:id])

    respond_to do |format|
      if @dude.update_attributes(params[:dude])
        format.html { redirect_to @dude, notice: 'Dude was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        # format.json { render json: @dude.errors, status: :unprocessable_entity }
        format.json { render xml: @dude.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dudes/1
  # DELETE /dudes/1.json
  def destroy
    @dude = Dude.find(params[:id])
    @dude.destroy

    respond_to do |format|
      format.html { redirect_to dudes_url }
      format.json { head :no_content }
      format.xml { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dudes_helper.rb
module DudesHelper
end

app/views/dudes/_form.html.erb
<%= form_for(@dude) do |f| %>
  <% if @dude.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dude.errors.count, "error") %> prohibited this dude from being saved:</h2>

      <ul>
      <% @dude.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_area :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_area :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dudes/edit.html.erb
<h1>Editing dude</h1>

<%= render 'form' %>

<%= link_to 'Show', @dude %> |
<%= link_to 'Back', dudes_path %>

app/views/dudes/index.html.erb
<h1>Listing dudes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Last name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dudes.each do |dude| %>
  <tr>
    <td><%= dude.name %></td>
    <td><%= dude.last_name %></td>
    <td><%= dude.age %></td>
    <td><%= link_to 'Show', dude %></td>
    <td><%= link_to 'Edit', edit_dude_path(dude) %></td>
    <td><%= link_to 'Destroy', dude, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dude', new_dude_path %>

app/views/dudes/new.html.erb
<h1>New dude</h1>

<%= render 'form' %>

<%= link_to 'Back', dudes_path %>

app/views/dudes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dude.name %>
</p>

<p>
  <b>Last name:</b>
  <%= @dude.last_name %>
</p>

<p>
  <b>Age:</b>
  <%= @dude.age %>
</p>


<%= link_to 'Edit', edit_dude_path(@dude) %> |
<%= link_to 'Back', dudes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeoDroid</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>